// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeQTirVPt9_gtM4rDBxQtEA06V4l_yNgQ',
    appId: '1:641079414866:web:c6d2c50299989c97a50f8b',
    messagingSenderId: '641079414866',
    projectId: 'pokedex-375c8',
    authDomain: 'pokedex-375c8.firebaseapp.com',
    storageBucket: 'pokedex-375c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb_PVl7Naa-RAxI6UTIM0mwDGwdULtTug',
    appId: '1:641079414866:android:59e053e2f40f4ea5a50f8b',
    messagingSenderId: '641079414866',
    projectId: 'pokedex-375c8',
    storageBucket: 'pokedex-375c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKsBpKE-5LrguOQcFS4wiQtbKC2S2tMXA',
    appId: '1:641079414866:ios:fc608ed20586bfb6a50f8b',
    messagingSenderId: '641079414866',
    projectId: 'pokedex-375c8',
    storageBucket: 'pokedex-375c8.firebasestorage.app',
    iosBundleId: 'com.example.helloApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKsBpKE-5LrguOQcFS4wiQtbKC2S2tMXA',
    appId: '1:641079414866:ios:fc608ed20586bfb6a50f8b',
    messagingSenderId: '641079414866',
    projectId: 'pokedex-375c8',
    storageBucket: 'pokedex-375c8.firebasestorage.app',
    iosBundleId: 'com.example.helloApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeQTirVPt9_gtM4rDBxQtEA06V4l_yNgQ',
    appId: '1:641079414866:web:043e7ff3c50a893ba50f8b',
    messagingSenderId: '641079414866',
    projectId: 'pokedex-375c8',
    authDomain: 'pokedex-375c8.firebaseapp.com',
    storageBucket: 'pokedex-375c8.firebasestorage.app',
  );
}
