// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjOdqCwF4-ajfzRddHv0oc3GLMlJiLOk0',
    appId: '1:1036471575814:web:ebdda8b26e0f29b37d2a87',
    messagingSenderId: '1036471575814',
    projectId: 'cineapp-flutter',
    authDomain: 'cineapp-flutter.firebaseapp.com',
    storageBucket: 'cineapp-flutter.firebasestorage.app',
    measurementId: 'G-RKM5REGP9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACQgerKCfkPGDu8Jm8bRVNgEBZ8yH2Iak',
    appId: '1:1036471575814:android:bcb9304b50562b5f7d2a87',
    messagingSenderId: '1036471575814',
    projectId: 'cineapp-flutter',
    storageBucket: 'cineapp-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Y2AYL9IRjzyMl9A9zhItL9EFkoDMp4o',
    appId: '1:1036471575814:ios:18fb843351bd87ae7d2a87',
    messagingSenderId: '1036471575814',
    projectId: 'cineapp-flutter',
    storageBucket: 'cineapp-flutter.firebasestorage.app',
    iosBundleId: 'com.example.helloApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Y2AYL9IRjzyMl9A9zhItL9EFkoDMp4o',
    appId: '1:1036471575814:ios:18fb843351bd87ae7d2a87',
    messagingSenderId: '1036471575814',
    projectId: 'cineapp-flutter',
    storageBucket: 'cineapp-flutter.firebasestorage.app',
    iosBundleId: 'com.example.helloApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjOdqCwF4-ajfzRddHv0oc3GLMlJiLOk0',
    appId: '1:1036471575814:web:d866d898cbf6aa057d2a87',
    messagingSenderId: '1036471575814',
    projectId: 'cineapp-flutter',
    authDomain: 'cineapp-flutter.firebaseapp.com',
    storageBucket: 'cineapp-flutter.firebasestorage.app',
    measurementId: 'G-RVB724KXW7',
  );

}